### ISSUE TITLE
WW2UK stopnie mają niepoprawnie przypisane insygnia.

### ISSUE THREAD

**Issue by Maciekkub** [Arma4Ever/A4ES#100]
**Opis problemu:**

WW2UK_szeregowy posiada insygnia Kaprala. Szeregowi żołnierze nie mieli chevronów (tych szerokich v na ramieniu).  Coś ala polski szeregowy tylko na brązowym tle i w formie prostokąta by odpowiadało szeregowemu żołnierzowi.

WW2UK_kapral posiada insygnia plutonowego. Kapral brytyjski posiada tylko jeden chevron.

WW2UK_sierzant posiada insygnia młodszego chorążego. Zwykły sierżant nie ma koronki nad chevronami. 

WW2UK_Podporucznik posiada insygnia porucznika. Podporucznik posiada tylko jedną gwiazdkę. 

**Wpływ na grę:**

Psuje immersje.  

**Sugerowana zmiana:**

Korekta nazw stopni, dodanie ikony dla szeregowego. Ewentualne dodanie brakujących stopni (kapral, sierżant).

**Comment by Krzyciu** [comment]
Ok dzięki za feedback, poprawimy.
Z ciekawości jesteś członkiem naszej grupy? Jeżeli tak to prośba żebyś się zgłosił na TS3.
